apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cryptobot-controller.serviceAccountName" . }}-edit
subjects:
- kind: ServiceAccount
  name: {{ include "cryptobot-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cryptobot-controller.serviceAccountName" . }}-edit
  apiGroup: rbac.authorization.k8s.io
