apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cryptobot-controller.serviceAccountName" . }}-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["cryptobot.com"]
    resources: ["bots"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
