---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cryptobot-controller.serviceAccountName" . }}-read
  namespace: cryptobot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cryptobot-controller.serviceAccountName" . }}-read
subjects:
- kind: ServiceAccount
  name: {{ include "cryptobot-controller.serviceAccountName" . }}
  namespace: cryptobot-operator
