apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cryptobot-operator.serviceAccountName" . }}-edit
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "cryptobot-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "cryptobot-operator.serviceAccountName" . }}-edit
  apiGroup: rbac.authorization.k8s.io
