# Cryptobot

controller:
  config:
    enable-modsecurity: "true"
    enable-owasp-modsecurity-crs: "true"
  service:
    externalTrafficPolicy: "Local"
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true" 
