# Chart: grafana/loki-stack
# Version: 2.8.4

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production

    hosts:
      - grafana.cryptobot.germainlefebvre.fr
    tls:
      - hosts:
          - grafana.cryptobot.germainlefebvre.fr
        secretName: grafana-cryptobot-cert

prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: true
      size: 2Gi
  server:
    persistentVolume:
      enabled: true
      size: 8Gi

loki:
  persistence:
    enabled: true
    size: 5Gi
