apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cryptobot-operator.serviceAccountName" . }}-edit
  namespace: {{ .Release.Namespace }}
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: ["kopf.dev"]
    resources: [kopfpe"erings]
    verbs: ["list", "watch", "patch", "get"]
  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
