architecture: replication

auth:
  enabled: true
  sentinel: false
  password: "password"

commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  # Set maxmemory cache limitation
  maxmemory 50mb

master:
  disableCommands: []
  resources:
    limits: {}
    requests: {}
  persistence:
    enabled: true
    size: 1Gi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - redis
          topologyKey: "kubernetes.io/hostname"

replica:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - redis
          topologyKey: "kubernetes.io/hostname"

sentinel:
  enabled: true

metrics:
  enabled: true
