architecture: replication

auth:
  enabled: true
  sentinel:
    enabled: false
  password: "password"

master:
  resources:
    limits: {}
    requests: {}
  persistence:
    enabled: true
    size: 1Gi

sentinel:
  enabled: true

metrics:
  enabled: true
