architecture: replication

auth:
  enabled: true
  sentinel: false
  password: "password"

master:
  disableCommands: []
  resources:
    limits: {}
    requests: {}
  persistence:
    enabled: true
    size: 1Gi

sentinel:
  enabled: true

metrics:
  enabled: true
